[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "e1d8d8012700175b4d56d6b6e9ddb8d44c846dcb"
os = "macos"

    [[Rclone.download]]
    sha256 = "65692bba35b33ca0d2602b6d6e04a8a16bdb4765be7d047b4b3cb288a9b58261"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "4b1a6e37caa63c367143e8df11eee13f33da2dfc"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "2b5120b0b9b8a43a54c153fb84d337f67dd3325908ae2e150439d622863eb93f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "4b1a6e37caa63c367143e8df11eee13f33da2dfc"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "2b5120b0b9b8a43a54c153fb84d337f67dd3325908ae2e150439d622863eb93f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "c3524650f437336c4b4128afd620999a54c5d2d0"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7bdc7f221c7dfc26613808862c157ed8804039b3e39f595f94dd402b6a65088a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "c3524650f437336c4b4128afd620999a54c5d2d0"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "7bdc7f221c7dfc26613808862c157ed8804039b3e39f595f94dd402b6a65088a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "a6d9ffb67e81729b83365ce2d441f8b20f91e233"
os = "windows"

    [[Rclone.download]]
    sha256 = "33328f3d8aa2439704b5b2a6f14f6db7ccb63229a2b1237492dbd9eaefce8b42"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "e8322713bc045db801880e810dd8b4add624d2a4"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "ab5443fc23e36ffe502353ca3d3cc56fbbf98133aa9634484f3964e8cf9cc762"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "429999d852788feccf3122197942fd2556c9bb1f"
os = "macos"

    [[Rclone.download]]
    sha256 = "8600d7e2867c20b57ba84bc070d7bc450442cdc4383eb725736a9f99e0c70950"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "1310193e5dfc4fc4eeed6be9a2a579ffaff610cc"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "edcf5f32311c2ea21df678dbe008afb6bb559f640a13fe4a58ae3b9a8826b87b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "03ddb0a355f6aa6c0cd848d87d938abcae5854d8"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "67580e8b3bc707c9b0bb1e1b3f0cf8ddce85aadb077ca2d84867a935bad1cfa0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "24a3607cc2a21d8d8e70b1954b6dd46c276fc4ab"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "87af80ff1db277aba7c1020e4f6cf43e38cb65cb1037d483714b45dc1eeda063"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "7005693ca05d9127eb88e24f52acddfe28082709"
os = "windows"

    [[Rclone.download]]
    sha256 = "2b1602ac828355a2d12231e24b3262cfad09083223351cea150bb8099c21695b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.67.0+0/Rclone.v1.67.0.x86_64-w64-mingw32.tar.gz"
