[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "9253e7d050bdef48a5cdcffbc94ef19754af030b"
os = "macos"

    [[Rclone.download]]
    sha256 = "a0aa680a4577ae87128003f31743de88f2f21a2f1b6cbfba44b4dc2188b8651b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "d20362e428ad0b31197ffcffefe16b3f53dbe550"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7ca720a3d74c26b1881a23402589ee44a2a8733bbe0812b1f2bbcc3b27611087"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "d20362e428ad0b31197ffcffefe16b3f53dbe550"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "7ca720a3d74c26b1881a23402589ee44a2a8733bbe0812b1f2bbcc3b27611087"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22b00d02f3f1810bca5674ab6db632a8bc7b8477"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "08ee2862e893013effa6fbbc9b2b73a304e423570e02575c74f609bc3b8fa26c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "22b00d02f3f1810bca5674ab6db632a8bc7b8477"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "08ee2862e893013effa6fbbc9b2b73a304e423570e02575c74f609bc3b8fa26c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96b0a7b0074cfc6036cb0ba5ba1d27467f65c0ae"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d27594a29d5ea7b75e9ed7bd8e858893acd6a121c18c50c331aa7d81c808d7ef"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96b0a7b0074cfc6036cb0ba5ba1d27467f65c0ae"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "d27594a29d5ea7b75e9ed7bd8e858893acd6a121c18c50c331aa7d81c808d7ef"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "f7e3db6df1d6e235d19dbb22e1d242e9aa4312b6"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "17993fcf3e37b5401d5b929103cea7b161fcaeea6cee4b687ae132d0bd86dca1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "f7e3db6df1d6e235d19dbb22e1d242e9aa4312b6"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "17993fcf3e37b5401d5b929103cea7b161fcaeea6cee4b687ae132d0bd86dca1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "44674fdc35abb562548374071063327d1c9c6aaa"
os = "windows"

    [[Rclone.download]]
    sha256 = "699901e389fb5b1f71cbf020bbd5d6c566b7a8515b2b9cb9be1e97e9b31ef55f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "5585207d5a76aea91330ca400c533e05754aa76b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "56016b9ebd9b50f171fd5ad709da9b3739b54548eb49b48ab45fd982a78482ab"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "8d7301461453fa27807c863f6a6f317d8a3c0fa7"
os = "macos"

    [[Rclone.download]]
    sha256 = "a8841b3e9c0f20629828d1cdb7083a37b473c66d2f95d1f0eb9d05c8f8000583"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "1d07e47bfa4624ec3308e7f9f812f4d1d6ddaef8"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "e0a5d59a31fc8df376774f57d783c1a2051366a96a5d18af7b155fd046406153"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "f931b5bb3b9a4374beb8d8968fd397985c83e2b0"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "8ca164cbb5e06b310621c89e2c42519c6960eb7490209becae393b8956d5378e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "7222d0571cae34ac427b7bb25d20ae140f29a631"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "82ce15204082771b55bde7445fc9a8ce14d399c9fa8508435563b8f9da83c1d6"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "69443df18699797dde5a27e9958ca67a582e1168"
os = "windows"

    [[Rclone.download]]
    sha256 = "30d99904c2d81990b7a6bd0a8bc96a4c123d1517fa8fd478c585268dddbfe15d"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.60.1+0/Rclone.v1.60.1.x86_64-w64-mingw32.tar.gz"
