[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "928e82b245a0913dc9095e9328e84e8eb4469923"
os = "macos"

    [[Rclone.download]]
    sha256 = "8f53e2bb0c65524037f162623a1a1f95f29559d2855db79af788fd95f81762ae"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "0388c65186e2b80ff6d2cf66fb517ddabf424212"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "46d18170ebc8d2e6f311b88f666b2f80bc4018dd2d9ccae1eaeb282a0e03bd4a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "0388c65186e2b80ff6d2cf66fb517ddabf424212"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "46d18170ebc8d2e6f311b88f666b2f80bc4018dd2d9ccae1eaeb282a0e03bd4a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "1dbc74a008161bead827f6d0dea2f19bba5985eb"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "0d809241d478b0b4efdaa8f121d0f4e2384dc07faacfc7cd9fa249a64d5622f1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "1dbc74a008161bead827f6d0dea2f19bba5985eb"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "0d809241d478b0b4efdaa8f121d0f4e2384dc07faacfc7cd9fa249a64d5622f1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "d9451e48f84e7a5ca3c2f3285d8eebbc6eb13d1a"
os = "windows"

    [[Rclone.download]]
    sha256 = "225901b204e8459e29cb4f606afe7f73abc1bd5f0f1dbeace91cf5b69db69fa1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "8572892371d74c7973e5ca08bc9e050904b8895c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "35f34db9d65beaa7673798f45478b61e6e84c5eb00d313bd4b374c3019c7f8fc"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "c217b416e2a0fc1ca8fa1f72dbe5f8f2589c2b83"
os = "macos"

    [[Rclone.download]]
    sha256 = "b245913068e73700e7e3c292de56c9343536bba049cb968569f5bb4ef45c72a9"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "dc095f672fdb8be12626522363628f8a97fb492f"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "b70470fd82b25613bc4d5bee2a0244a4cc00649cabd3d16e6e7aa23c8bd2bf1a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "39272d85f2b0e9ccb01df86e2055dd7fb7d35686"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "c91d587c9c0db7c3d8c76f5480a374ee5b08b93968a1033514a19984d953b5d3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "95ca8d94a19e336bc8605e2c87b236774bdb902b"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "d7e86b09edcf6fdfc0eb477d13f35ab202d843461272237a31ff65502686dc80"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "d21a38691ac60d1332a1062fc330b6fe4a6bb23a"
os = "windows"

    [[Rclone.download]]
    sha256 = "ce1acd79cdf196559342dec042cb6970e015d2f1ae5c697c5ac7a5c4364f777b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.65.2+0/Rclone.v1.65.2.x86_64-w64-mingw32.tar.gz"
