[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "a2d9cf77cecbd5dd146320fef1a438d216ff1122"
os = "macos"

    [[Rclone.download]]
    sha256 = "e7c9d53eb0db376f1e11e0f4de8e54e42b4650eb211e4c465ab6e3a3cf8a68ae"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "930c53afaba9abee75f31ff97a28e3d015c7c513"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "dc24f99a46bfc2ac788f60ee3ec395b3fe783509e1a435440c25728788c77d7c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "930c53afaba9abee75f31ff97a28e3d015c7c513"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "dc24f99a46bfc2ac788f60ee3ec395b3fe783509e1a435440c25728788c77d7c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58d4bcbcd59119be34cfb0c75a2a20bf943ca32a"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "30cc45fc52c46c0613fa2ed3f5cd8f893523d6581a7564166d3b77a36e06c7f2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "58d4bcbcd59119be34cfb0c75a2a20bf943ca32a"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "30cc45fc52c46c0613fa2ed3f5cd8f893523d6581a7564166d3b77a36e06c7f2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4ba3b6ddc5c9f71bbc39ea69f3c2e9272980b8d"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "e862bd28b8337d70ce8dcb2c962802972ad3b711e45ee40cb5ce079bc13a9544"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d4ba3b6ddc5c9f71bbc39ea69f3c2e9272980b8d"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "e862bd28b8337d70ce8dcb2c962802972ad3b711e45ee40cb5ce079bc13a9544"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "05500eed0b238cae5b9864c82d1f632d5ee20d85"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f6e2f316313b34a60c6d819c00309854743c5762688d78b5fbfba6c740a90261"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "05500eed0b238cae5b9864c82d1f632d5ee20d85"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "f6e2f316313b34a60c6d819c00309854743c5762688d78b5fbfba6c740a90261"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "27016aaab6db72d9c4acef386bf0a435baef1807"
os = "windows"

    [[Rclone.download]]
    sha256 = "06811a95154ad7ae95d6a032c1491eb9a5dcbcb8e0a60872146408af9f791cb5"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "c815b839b63692b55c7bf09ff081dc2fc930575c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f182d51562a700ac0ccacd9b507f4281d8072fdf168f4f2b8e508f9f1b7dee78"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "d342c61e291cea05f3d8a97fb392df5cc7ba465a"
os = "macos"

    [[Rclone.download]]
    sha256 = "49b95d29870f8fcb9b395ef28ad616fa3f6e078f9d94d8298cb6edb19e11bac0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "5466326a19f68175562065c97a0b7773a768b37b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "8a46504b2da73b4ec51d723022aaa5483c1cd13520286caad3954cccedef0d58"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "8abebf460cb18f4bb0e76f8598426026f1b95f4a"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "5c47c46819cce9eaf6658c886df005ecc5e90673d331818ee538f8109cf8afb6"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "11329e0d6e6ddf543a8fb7c2dc06bfecc140c4de"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "d36ab0400ece9cbc4a599a3fd831e1e46a5ed5357ac5b618141fd85153319ba7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "aa29aafd9707242b881bf18fb24073201b47cfbe"
os = "windows"

    [[Rclone.download]]
    sha256 = "03a2d7082aaaab3217629cd44b2c5fc3fb544ee112031a686b31c608f948ec14"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.63.1+0/Rclone.v1.63.1.x86_64-w64-mingw32.tar.gz"
