[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "1ef931efda7d147bda9792cdce45ec87bf775ebf"
os = "macos"

    [[Rclone.download]]
    sha256 = "cfe05575da3073df48aef7a99623a526b3ab843070b2bff16ea5ffbbfbb1eccf"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "d550298a36204c30b6ab68cf28d32418c9c4bda1"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "e9fcf7c9a6dd2f5e0cecb4b31a1cf57f6ef7fee5d14b5fe9e13cb9d8fa277d8a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "19344ec98a98ceb7b9aa6bf3a9750cbf77306a20"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "88019b40c51870ef92e5ee752b4d0395d690dfbcb808d9aee33379785798a837"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9be34a89704595128a4bd990a0e9d7a9e37226c1"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "1c5a7ec52cce73970f5f27643e2e0770cde6b990da581f98db3ae866179f8294"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d376a0af3f926e7267e22bf43adf4706bcb742f9"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "40d71d4f8af21b9cbadab120be5475a391dafad6f8bc9e8d306bbb5c9b76b416"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "70fe698a4e8a067894d51299c8cf11dd1d706cb9"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "adb8ef0fbfe80df408f37cb172b57d8e00fc1b8d27e3b18f60c79f482902cfcb"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1e9d7b94c239284c4fe4cd44a8de8b681e2a1ff6"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "3f452afbeb8e871110079ebb33eea22efe5cad2831d7db35fd51b9292843897e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "67b7b3c422ae3ff253a17f2a84127635980feba9"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "a6097ff02503f5fd98bc012741b4b9cb2284581256a5e8ea4dc64ac4c7b3cada"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "dbef98d242e31d642dd42d5d7c966459defb38fd"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "86c6a9cd5b84b4fade93f7883d5d93c3bc8bed45605e21fcd185359b7d79bb11"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "a31eec693f65f44b0a44bcaaa7472d9f8e08eb8b"
os = "windows"

    [[Rclone.download]]
    sha256 = "2ec02b886e751a38a025cd13c86e41d63dffb8953f6e635386d7cd8a01229abf"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "4538fa0ea9a1811281d586037fd9dfedd988b659"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "c37453e864ac1f992706b89e12d603cf9b907c64e4254ae0c174123520ac5109"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "97c8b7373001940286bd03ffbf4a0bba091de286"
os = "macos"

    [[Rclone.download]]
    sha256 = "a6e51ce3bfa940b365db5bfca475357944686b5d5df35b2d341aff593b86a9b6"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "9cb2f3e7957abcb02c988795eb525a64e5eed24c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "5df61c8fa43ae5c4fe61ae4f5d15633b94ea6363fc9abc196ca9d3f4611a61e7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "1efc29ca38af6a755e1f2cd7c9f7255074b4574a"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "d14496c2e7677b52547e9cfe34891bfb3268cae00583a2995801a1fb0267bb59"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "edde167c9e71783534628e5988ec6aa385b04a04"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "08e8c9ddad83b38b79a595ac027f974320c12c4f976eefd7645604064f6cea94"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "47cb210268db37ea616db30d8e9411b3fd0092c2"
os = "windows"

    [[Rclone.download]]
    sha256 = "cde2b6d3a10d309f8f4ca78b29632425749f72684b34ca09a80432565973e454"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.58.1+0/Rclone.v1.58.1.x86_64-w64-mingw32.tar.gz"
