[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "93d4974f766799d64e8222ba821241e89f8c0069"
os = "macos"

    [[Rclone.download]]
    sha256 = "6328250618a53132eb517cf07bbddc522e007e397a0f73fd0f79fc010c38398c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "340d51f5870589f5f2997f32b8108fdb754fcb68"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7e4abfcf8c398d097fe9260be560f95f3903c20f58d659a29eb408ba82256d18"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "521caa3c9a4fa8fdf62ecb5b94cbb2215f6d1837"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "b689cb292b6a0ca8b280a338af7b17026a0d118fe3d7e330da533028f14f13d6"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c461cd5f43da355a807ebb067700dc2dea2336f7"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7bc31158068f895cf6c0c86c9a585bd8bd7f400abbb95d5e26d44aa01a2691a9"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a65e13b2f79c01da81e61a69786b5852e876d18"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "73acc60a034df33f669890c63259cefbbe299eee28d326535782da707569ee85"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "abd67d637af3094409147eb1333a37943150a02a"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "711287df4cea567dfa94438f04d3cd7acc98240b2e09e9fc52c411f9f4c5777d"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2e50d961303f0c2c3acc527a45677960b9bc096d"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "5665999311e2d7bdd5d87599e59fc62332ca0701beeea0b503d8264bdc528122"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "20c46ab325ab58b6772ec4dce1da8404793af50c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "eeb098674ff43bb7afdcea2f83cfa5bf4a45184196144c05a69bb7678c4c23f7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "24ddb204c855954bcc6d29739f4c74a3a7ee85b5"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "34e53ba722334814ac79e3cc0bd1da29d0f2ff0b431ac9a3819b55ba7a73110f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "a1d2e8c75453f2a8babacbc1d8d6566d4168fbc4"
os = "windows"

    [[Rclone.download]]
    sha256 = "8c64f9f3b325b43334076a414bfa622e132497d652ef3ceaad100b5e4d94e411"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "e7ef1df2d67cf859dddf34958bee89592b261c55"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7d1ab4c99b1719b7b90a2e079f78a9b5671ab06bff004a4754088f60cf1189a6"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "2113a370313422d8ca6ef04812a9ed5ecb8a4ea2"
os = "macos"

    [[Rclone.download]]
    sha256 = "c15a7f34097b92e060c447268d7f147b6a4389a6d406820735296c604d755b1e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "75197324ce6d4e99e84f4526362645ece8c988fd"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "239e362f64f0d23c2cc6c5b8de16a1dc13f1898c01944f1f6f85485ee0bd075c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "25fa120bfb8b46e4085b025ffa698b016e78cd98"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "8c970b6d066b1a883aa7e5bfe1556929a71ddd3770e855ba16cd064e7dae0119"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "7beb2ee0511e7fee7f41be0c23ba0d1ab39782db"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "bd8978dad4c16697b156b017aa276049f6f903a96bbb2ab4e4c16e9e0b25ed42"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "570b29838afec56905ffbee8c6311af3f0befba8"
os = "windows"

    [[Rclone.download]]
    sha256 = "5090dcecd7e262c692d9aa86b4c9380271a42e87bfd45b5d4e27a33cc57c0a12"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.1+0/Rclone.v1.59.1.x86_64-w64-mingw32.tar.gz"
