[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "99947444b5def6249c678b281be45dcfef0305a7"
os = "macos"

    [[Rclone.download]]
    sha256 = "ed2156e75673d73e7ff779a8a7d5d4bd83937c891b189a251cb4e49da73cb18f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "aa28528a444f4205d24b7fa6a936f65f3693fc1c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "c30d448395133f266df1069f85e995dfeb44c754243c4cfe0324e796089cb784"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "aa28528a444f4205d24b7fa6a936f65f3693fc1c"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "c30d448395133f266df1069f85e995dfeb44c754243c4cfe0324e796089cb784"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "c91cee19d42027d0a31dce9ece732dda6675289b"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "2f855a7db56f72e7c4974289071929a15990be08008c579291770d68612cf3ff"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "90a1c917e85d1aef5140b3fe69e3cd27ab241ee3"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "16dda87736340674cbb0b9fe1417537d371a2d2b5033030b718db3b63ab4d749"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "90a1c917e85d1aef5140b3fe69e3cd27ab241ee3"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "16dda87736340674cbb0b9fe1417537d371a2d2b5033030b718db3b63ab4d749"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "732e7cd0ff23b8d102fb970871b0dc6f883f0573"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "0653e7f561f571db9b710934bedf9da11ea2b62e3f515995527e44af788cbfdc"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "732e7cd0ff23b8d102fb970871b0dc6f883f0573"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "0653e7f561f571db9b710934bedf9da11ea2b62e3f515995527e44af788cbfdc"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "368f2961a7503749ab9cf14a4cbbab7d1c1a84e3"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "372ae5dd9132f6832a7653570a0a9cc66e64e0305edf465a85e725946dd457a4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "368f2961a7503749ab9cf14a4cbbab7d1c1a84e3"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "372ae5dd9132f6832a7653570a0a9cc66e64e0305edf465a85e725946dd457a4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "22c9a097a58cf0b62e3eea9ca6db9a054cd6c391"
os = "windows"

    [[Rclone.download]]
    sha256 = "6043ba88f300ccd1968c468c179dd6e2815b01ff3112a045c1d3e7e0c1dad2d3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "260ddf155fcddebd8fbfe63fdfe5dd9894ffe636"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "0083b960c5f2ac110ac90a8f31a23add675d46ab3c55688ac4fec4ac0e9ecce5"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "ca7d445f6d6d7f274d3f71f4568a41d5189220ac"
os = "macos"

    [[Rclone.download]]
    sha256 = "24da92cf46a62ccf72c87d70dd7308a9d9aa34218e9bbd6cc91a2fc28db1bc39"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "5369e734cebac64a352c7352e940a212d8e37090"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d578732638648b5409ca716fad027ab2a38fd94c2acc4bc1ede1a44f5f271f46"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "fd1f9f30dae933a63bbe222bed86f217bb6871e2"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "c8508c864fa9519a252928be14e33a436b79fa94dabcf3d3e3900206d70d12d9"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "3a7fdf0820cfda47999e9bb0855ea7d9dd8ac4ca"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "dbfd29dd108e7378fa0a73640aa41e387f18026d9ea7dfe401408a2458c9bbf4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "ac5e8b0ccf476e6c2ad0ed743775e91faac74b58"
os = "windows"

    [[Rclone.download]]
    sha256 = "0171cb8ac3e1852a0e76d311794a34a594c1142e2a7175a90b9f9201fd60c57d"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.2+0/Rclone.v1.68.2.x86_64-w64-mingw32.tar.gz"
