[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "8f6a8f265b37319a17a5a1e96c3cb5a56c694131"
os = "macos"

    [[Rclone.download]]
    sha256 = "77074c4b076646b4be7348a31cc16a6e78c968b7f45c74a28e5666ccadaed374"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "13fa6e7ca6e67f822fb9cb2c5101454e46f41bdd"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "ada437c78637ae1d06376972b1fd456536f610d9cd8992f326325958a6eed66a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "13fa6e7ca6e67f822fb9cb2c5101454e46f41bdd"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "ada437c78637ae1d06376972b1fd456536f610d9cd8992f326325958a6eed66a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "7e1a6650d030df4150f97f920afc71a90ec8f350"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "7f21cc256cc772ef689630db2d4bd30bbcfc839497cdcb6ecc3021c7f936bdfc"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cce573eba9cab59146242126b73d9b8d3ce440cd"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "5b0c1e027f9b64db658e0eb8c14d722dac2c7d0643ec373710b0cec98c07cbf3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cce573eba9cab59146242126b73d9b8d3ce440cd"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "5b0c1e027f9b64db658e0eb8c14d722dac2c7d0643ec373710b0cec98c07cbf3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc8c0119064783cecf5afea4c511183ed6d85715"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "2f88f446222da6ca0b2504129d8d0f93436233ed051dc44d829cca5ce540de7a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc8c0119064783cecf5afea4c511183ed6d85715"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "2f88f446222da6ca0b2504129d8d0f93436233ed051dc44d829cca5ce540de7a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "8ba73bc09da77da165655afba042470e4a927f62"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f51d0b33fd136cc45d2bd9f13c0ef3ff724ed63f5c36bc80c361f0b60d0671fb"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "8ba73bc09da77da165655afba042470e4a927f62"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "f51d0b33fd136cc45d2bd9f13c0ef3ff724ed63f5c36bc80c361f0b60d0671fb"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "53f222b4122962bfef3b06985058ddefff6193f2"
os = "windows"

    [[Rclone.download]]
    sha256 = "3e04726f1e9bd559180fd5435b0068313c3ce72d8eeb8e300b24ba16b95a8bfb"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "7a186bb286ae46910eaa8be2584e9219240198c3"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "20a48d1883669b52b6fa470b2bacfc4feea84ab362c3466d27f66b5b5a9c1760"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "5c09501819ffbc7c553ac0b237cfa47a4ae79510"
os = "macos"

    [[Rclone.download]]
    sha256 = "ec0950aced64c3a05e3d37b4f8f647ec8c1ba74e12399c2028f9f3b811e66162"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "c97ad548a0df136e46cc79932d924e927a230d0e"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "756920c0df9b2fabaa92944af654024706ab004154f26509804df721e13dafe2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "715dc85462b3304ebaf21c3dff01e83bbc9f936a"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "b483e0376b64953012c65fcd494beafd17fb21496754c0328700e82cbc780ac2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "17434f6e520c777fc1c1c699afbdaf72198b4592"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "9f00deab350bffd2122a38ff339d7aa6caacd9583f9e2a65f0d791fd8c72b63a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "ef2a711aa29b7dd26e60c4e6bc7f99ce1e3538c0"
os = "windows"

    [[Rclone.download]]
    sha256 = "f28fc966d82c7b10e6669bb1a99be3762db6ca9759d51daa2e4a745f670c3120"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.1+0/Rclone.v1.68.1.x86_64-w64-mingw32.tar.gz"
