[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "600f8602b039abcd60215e4aad84897190f64995"
os = "macos"

    [[Rclone.download]]
    sha256 = "20037def3e598d5757b4bac96d421f46bc170803ad629ebce3cd7c3b36cc85bc"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "734e06e7b18912cd752699c53e10fb6ff0fea9d7"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "0da0ea9ff634af87d97166e918e4f9b7cb7b71a170ec1359f4481a8ab3f47654"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "734e06e7b18912cd752699c53e10fb6ff0fea9d7"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "0da0ea9ff634af87d97166e918e4f9b7cb7b71a170ec1359f4481a8ab3f47654"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "74f37b6a9c1f7ce11581c1c2f090014b1f2819f9"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d1ee172d7642af8a6f0a864e5ce08ff789804e67aef06808b72bf7f41dfe4f20"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "74f37b6a9c1f7ce11581c1c2f090014b1f2819f9"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "d1ee172d7642af8a6f0a864e5ce08ff789804e67aef06808b72bf7f41dfe4f20"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ef47f2dc75760ea14beb2ac9ee61627a8544182"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "2125f1b6979849d6efb4e1c2348468f409cec1f90ba0a1a83e136ec4dd6793d8"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4ef47f2dc75760ea14beb2ac9ee61627a8544182"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "2125f1b6979849d6efb4e1c2348468f409cec1f90ba0a1a83e136ec4dd6793d8"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "08df9ec59c882ea0be6d2390a31c3dfa715599f7"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "6d1d24846b64f1606a05e9ec6addfc90f418f6687ccb062d33040d1d24c769f0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "08df9ec59c882ea0be6d2390a31c3dfa715599f7"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "6d1d24846b64f1606a05e9ec6addfc90f418f6687ccb062d33040d1d24c769f0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "841b4743fe6a21f9d5792864359a682c55878e0b"
os = "windows"

    [[Rclone.download]]
    sha256 = "96fc8c365bdd9fcdcc03bfb603afb1aabb63769ca5f285b27c922812be4ac5ad"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "064db00bdc2aa3823296879c8baaa643e44d5331"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "2a2f192d129086adeaae722ebf15ff8fd41ea87458fa322f417470db198fe7ee"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "9d1e84b880efb2e2c90d388c6350f23cad978ee0"
os = "macos"

    [[Rclone.download]]
    sha256 = "805545a2242a1c9b80873a81300a9fefd7fc9c53495266ca27945d8dc6da70e1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "d62f2650cafb9ae63be9d0041120ad5b327f9c55"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "1b05d8495c94423a02992d9d9701f6e8eb18e4d654e6c20964327ac08174a592"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "5e162c622ece74df638c2c7ebbb06996769380e8"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "91bd58b41ed164dc81821615b43a7b41b7a4d5f5e9b0fd874f71edae431bac55"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "f6df6face4513dbe7f8dab365293b341acb3a6ab"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "9196c32f97993e35235c50ff3ccc57698fceba9c7e402059f15ba21548699744"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "21ae77a9778f4bdb2426b111f3fb046e4af90c62"
os = "windows"

    [[Rclone.download]]
    sha256 = "644fc8a764e5b212016c2d43dea1c725153838a8b453a79cc8b821e6c4dcf507"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.68.0+0/Rclone.v1.68.0.x86_64-w64-mingw32.tar.gz"
