[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "53fb183167679a605dfafa95f4c5ea6f46db0f34"
os = "macos"

    [[Rclone.download]]
    sha256 = "3e1dcde996ff815329aeee85559acb472de8e3a6f688d3c0a5f0e3a9e414da1b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "0ed425d1ee907ec3ba3808cc4e59621431644013"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f8b9d7a91569fa4b56d156e6cba322775137864f8a5384a8e362e1f69b3edd1e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "0ed425d1ee907ec3ba3808cc4e59621431644013"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "f8b9d7a91569fa4b56d156e6cba322775137864f8a5384a8e362e1f69b3edd1e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "74bdb6397a5afc8e85d05b432dd4f3e105b06c03"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "936b031fd3d80a7f06071acab7a3e19eacb0c79ddba2169a6ed0500bb001ecca"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "033412248c465b3faba1fd897b0a592120bb0bbf"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "8676b1279192fd0bbdc8be3a483e8e8f195746b088776468b0d4cca958166502"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "033412248c465b3faba1fd897b0a592120bb0bbf"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "8676b1279192fd0bbdc8be3a483e8e8f195746b088776468b0d4cca958166502"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb2080d5803b5a27e0e94ab10da5603cdbc971d7"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "ce1a3b23c526efcac8ed7817f4e6704bb4ccc03a85c7271469008f6f38085a08"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb2080d5803b5a27e0e94ab10da5603cdbc971d7"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "ce1a3b23c526efcac8ed7817f4e6704bb4ccc03a85c7271469008f6f38085a08"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "742f6e410cd2e53372a3ced21b9b9707ab4361b6"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "cafd233040bbf6eca7fb99c22468e47147836d248d3275a55fee9459585777c4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "742f6e410cd2e53372a3ced21b9b9707ab4361b6"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "cafd233040bbf6eca7fb99c22468e47147836d248d3275a55fee9459585777c4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "9871cf38b1eabf4be1598d3aa2533b9346d817e4"
os = "windows"

    [[Rclone.download]]
    sha256 = "28ea1d4de54fc4a57122103327084506761792a14a3f72387f1156d3fa644dc7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "1a2db9a2c6e4fced9a6350068578850129a1aa54"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "59bf529b48cff3a25810f70c2d9bc2a8f98245dd16fce3333852f8b9080e49c0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "riscv64"
git-tree-sha1 = "9d995186f4bf3db3b3ae774df821e3621ee4ac0d"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d5ece5012b2bfbb40e53e3fa06e99f89043bc89de0d1f9a02235a24faf460962"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.riscv64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "846f2a4c66e92243a8def8b2df4990e3c247e33b"
os = "macos"

    [[Rclone.download]]
    sha256 = "443880e36f2e358cdfcd1f99ee42ffd00b9d477785e0a71834a95ba40ce39fc1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "2a84c4dab75a4890f23d373c491cb7c5f9103420"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d3badee62b4bed728dc93666b331f18af7818672b1bf21cf98e52358d9eef6b9"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "d05d61d2cd8ec804536fa4ecd5aa1a324cd7f2e9"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "ec5abb4960eec7a76580498f7f28f8d58043755590db218a6cd93e57e41c04a0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "39fd23203744c790830642cea11e367f6803474c"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "9f210390ecf03ef991a2f3fe0e5b4de04d59f7b48ea37262192f615febead626"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "7b493e56587e99ef6ea8934b0e5a023f9a91befc"
os = "windows"

    [[Rclone.download]]
    sha256 = "aa3faec8440c863707a283472408bf68431588d8be6f616c202a9c3310016c3f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.3+0/Rclone.v1.69.3.x86_64-w64-mingw32.tar.gz"
