[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "6a0d09e0cb1d32195414bcf5f57b2d867f0dda70"
os = "macos"

    [[Rclone.download]]
    sha256 = "a9747353fbf032af7b6b3e74b2559991d2c29da2f08bbd82cfb53afe15b24499"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "ba2cf58d86c7c970238820feace391d758e2a344"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "a768f9af36fa0d83dd13abd6a582d8945cd977db5cff192050ea5fb8f9f02ca2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "ba2cf58d86c7c970238820feace391d758e2a344"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "a768f9af36fa0d83dd13abd6a582d8945cd977db5cff192050ea5fb8f9f02ca2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "f3a4a0b018915e4f5918614de07c6e5c8734ff23"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "2d08cdf53262d9d76d4438133d752c13eaeeea2b509f1da46372b8841e708710"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "935a1ce4464dcd537d59ce9dc89820bda20ef43e"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "35b4a4bd990477cbf96192220604853b2991cf7f769532f52c87284dbc408b58"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "935a1ce4464dcd537d59ce9dc89820bda20ef43e"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "35b4a4bd990477cbf96192220604853b2991cf7f769532f52c87284dbc408b58"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6221e9bd56f50fe9a290211f800eb5c3ff97d58f"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "fe8870f101de680faa1c0a17924dbac0cea12f4c47d3090f2514e9e59f8da46e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6221e9bd56f50fe9a290211f800eb5c3ff97d58f"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "fe8870f101de680faa1c0a17924dbac0cea12f4c47d3090f2514e9e59f8da46e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "dcaa8e0dd6c6c7a67dc1e94bf1ea5dad9318a550"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "6b98083db30097b72ad4d041417c6caff1570c4a59cf946ef4ceedd84b8288d2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "dcaa8e0dd6c6c7a67dc1e94bf1ea5dad9318a550"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "6b98083db30097b72ad4d041417c6caff1570c4a59cf946ef4ceedd84b8288d2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "cd7d7f83fe1fbac87a4e7f245e11eb72e282e34e"
os = "windows"

    [[Rclone.download]]
    sha256 = "180928a13fb458ca1b76d0c11e262d1ee1f69a5486ac606ca60ae930f5d3356b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "a2d538f8f5bc5d0b0cb46bead4ba42d5e754fea9"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "0fb63f9d0958d67d2cc979d57d407815632173ba1a2956deb62de318586f120a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "riscv64"
git-tree-sha1 = "e2c3773a23492d094c2e3cbb760e07774e112417"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "5d6a284a61e5da169aea876438305847070c29c148a8c6e81627a69f24f75d96"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.riscv64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "ba20fcc0f8b99cc480a8a8a74cddc7652f10d07c"
os = "macos"

    [[Rclone.download]]
    sha256 = "49c8ee8c057566bf8839de9b5021ef851086fbd18c9ffa0478c9f2eda1f84113"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "645cfc3d842dbe22d8db341a8d6f797f534577a5"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7a630ae7e6680edf87d031a11c99aad8b51a2af7e1d0952f8e2c60c4963adb0c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "095f330b01bd6ffe2a9a12bd4d869d9e35660aec"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "eaaf53ca8c36786e22ea4f8f4c8b188a46a06e062b8899640305c870d6e1b8ea"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "522765d8cb4e9a5581eaf2dec0935f3f90eb01dc"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "cd2f27b77b2958169e25b28d6daaa95f59ca643e0887fbe9f2064890b08f7666"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "67105000e60ffa9e405b3a4f359f8d355b36c5e8"
os = "windows"

    [[Rclone.download]]
    sha256 = "be9a6cebc6c2bab532d99ae30f5f733b07eb1c3e142aa05a36947bca2a109ae7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.1+0/Rclone.v1.69.1.x86_64-w64-mingw32.tar.gz"
