[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "183878d8458bbed57b225e4f123e8013ea0cf0e9"
os = "macos"

    [[Rclone.download]]
    sha256 = "32f04464b34cdde44b8144e08d9bf4cd4145985133ce505e174bdb2d350f6911"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "66a7c1b1e6bf73bb3486ca0b88bcfa69128097de"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f414825ad7ff87e996d3927fd998d4aac46f8367bd622c43ee6eec57df2efe45"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "66a7c1b1e6bf73bb3486ca0b88bcfa69128097de"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "f414825ad7ff87e996d3927fd998d4aac46f8367bd622c43ee6eec57df2efe45"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "4fcfe2eab233ff99103f5d25419417e04bd26eee"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "7de25e351454123265b4c458709de2e4098c6ce738d7f631bac03402b8b4cc70"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5433a868bcda05f425e1c6fc8e2fecb2c1933c58"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "3b06f581125abdb1f073a6a7d4457de5f387edd0d0f00b262054d39081f251a0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5433a868bcda05f425e1c6fc8e2fecb2c1933c58"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "3b06f581125abdb1f073a6a7d4457de5f387edd0d0f00b262054d39081f251a0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d35795d113ebee78e7a065fd2b2542194a9c345b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "892b144f3bf870678de31e8fb9581c52963f4187a0199d9c4af887c9f46f5142"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d35795d113ebee78e7a065fd2b2542194a9c345b"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "892b144f3bf870678de31e8fb9581c52963f4187a0199d9c4af887c9f46f5142"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "d50a2222f236e543bf7bacfc54e111081fe1493a"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "690b5fc019a996300524796814eed34aa9b7a0acf9c025140715627940a26643"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "d50a2222f236e543bf7bacfc54e111081fe1493a"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "690b5fc019a996300524796814eed34aa9b7a0acf9c025140715627940a26643"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "4421be6fc9cdcab365e4dc5fde3c49efebe47928"
os = "windows"

    [[Rclone.download]]
    sha256 = "4591202f8929eed2f3bd1c2ffc4c7d5c7f7960f34e965a5ce427a49b5215c16e"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "e6908ea002cbab14887f2d9b8524f081224ae109"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "c653ea07869714341f961f7b1d98aea4aa80e58a448a00154b2e69ce53cc836a"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "riscv64"
git-tree-sha1 = "766e20f80a821a5347242dcfbf88f618154c1a91"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7629866914cdaa14ce140b6df1cfe78d0355dd0e96ed8bfb58a503603a06afa3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.riscv64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "1189650163189db62aebcdf7995e3412fea8096f"
os = "macos"

    [[Rclone.download]]
    sha256 = "0e52d93576d75b56487e7de50bab8ff4371d530fec364b2826cabbdf3823ef99"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "d40b3cb774839164fc55f830ffae0e9d7c024da8"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "68d87b88d02bc51a0c9b57fb6d3c46c84eff1e1400bfdc229be1f028b62c64af"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "1a66333b940bc6530a0887bb44fe712cfc22af7a"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "ccf82fcf6b37554cdeedfa510edbe0726aaac91f0cef31ecf186bc44fdd79501"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "995411f69be2e3881ba6a129bd245d86d130fbc8"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "64a355d58926c31b145dd6f9d6fbfe7e3010cdddce6dd09070be79437d7399ca"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "549a4aad7ef7b7c5c3d3f157008ab9fdce14e8f3"
os = "windows"

    [[Rclone.download]]
    sha256 = "ed861becac44cf380a59fc69e12ee8d7c3330a65a126c0eef8c93667e469ceca"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.69.0+0/Rclone.v1.69.0.x86_64-w64-mingw32.tar.gz"
