[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "517a10ad2940c1508e4b9ccbeb2a072f1614c16f"
os = "macos"

    [[Rclone.download]]
    sha256 = "06b8a30baef059f7841117fe3aba19ff967026db60a2c72d7e86b108e03e8719"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "1836fddc09dda0b99f329e8d2d2d26b908e9062a"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "eab6e788a2aab61518ca23044644b128f880c0e43a3bfee079a20c8c31d18959"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "e59980b33cc1bdd1ca8f6a0428dc2732a7b13d0e"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "3322dc47ff78eaa4a7d5dcfcece3a80c3664c4378b0d0d8e077d284e4ff8d1ca"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6ba2c023f7723161ba0053733cff7ae4e3aea517"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f81d0abd3fee3bddd6312be92094b79870b1a795d21f9737b97780fd937f0b2c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "943bc4c349b24ec31faec6a9d2ffad1aea894e37"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "c31b939bb7a2285f4d5da8ae619ef99107336ac16d51045b1d9c6b2b8fafc2ec"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36a88f8415e13dde71d3c037a18900de43fe518c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "1d1c157dcbc80899dea2f1ae2abdf1509cfeec0e6f0a5dd8e06234a933fc998f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "eeeb1d31e470cfec80e7988e02f5dd215702c39a"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "16dcb39fc07a5d9ffe720dd60fd26d461f443e227bab68925581913a3e444fcb"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "fd702f7ef2554fcdef5e6e9ea53522f40618ba7b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "cff551f3349582d84465263ece7ce065342bb842d1a9bb6e96381ce9ac57af87"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "1e65bd5b292b00b4741f7db854a89257657ace02"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "23a1544df6d469cf3defa1f3e7a3a14f2fe56b44b3df6c9d36386bb41c0194b3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "f81617d0da21ed65b9f11a00d4d642e647ad4026"
os = "windows"

    [[Rclone.download]]
    sha256 = "defc1dcad471ffa3ef677dc646c0f685469e0f85da100c4f8131eea4bee4217f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "7f1f97a4d75fc851ad6d9e7ed6810094516c3856"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "efb21d86b9a5f3bf0816c9ce5f7ef11b81d45c3b82ffba2f2a4e43091bfb150c"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "61b9234861d93acf2dad12ba4e35ab571beb322d"
os = "macos"

    [[Rclone.download]]
    sha256 = "7828aad21e6c304cb01c5608f10974fc10f858e31dbf714d636d13d48aa67d37"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "402a5ac71978619c0b4385586902888d390f5e75"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "6c921e9654c15b4d44a92457f8c6b39349dbfbf5e8251b197c4cac1e815cafe4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "a991f668074cd0f3278e1b6a37d3a275e0e3b069"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "4bb7fc3e76ba450d2ca35fe3985febde1245d720a92c059039353e985b31ea86"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "a146a543dab9cafad9d0618cd3680364e4dd2997"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "41ed948c30836197d040506612ffb9eccecabbce01b7b42caf696cacfc44d377"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "a999126e4593a0f13ff9e41e7d5709becf1385a6"
os = "windows"

    [[Rclone.download]]
    sha256 = "8513303d2d5802aa1ebc186d7f50bd92b79d09e7de8452476029ca381f6cb519"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.59.0+0/Rclone.v1.59.0.x86_64-w64-mingw32.tar.gz"
