[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "fd279fde7d93aa9cdbde7b9574a352c3c3f11fd6"
os = "macos"

    [[Rclone.download]]
    sha256 = "708b6ef053b029ec9aa88ba24422b6a1ebe1d0f6ac7677ccc40abd288feb9de3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "f6df6d7367343bc9ebbf14f7fe098fdffa37b282"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "5e823b24387af6513c89eadb9f152bc0b5451e0a6cb39c0c33a399653317cfe7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "f6df6d7367343bc9ebbf14f7fe098fdffa37b282"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "5e823b24387af6513c89eadb9f152bc0b5451e0a6cb39c0c33a399653317cfe7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "2dd86ad9f0e8f041da401f61cd7949f7f1cf953a"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "c7567c957a72282ac1c4929b3a9b350f6678510551e8c6c16e6d6aa863e224c6"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aba6c4cff658419ec84a446cb3972d07ce575506"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "95b5841cb9282fca0c1a6602371677e032586eb1a330e2dbfb4b4d15ac371471"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aba6c4cff658419ec84a446cb3972d07ce575506"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "95b5841cb9282fca0c1a6602371677e032586eb1a330e2dbfb4b4d15ac371471"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8df8c0325286e1df1d253b8ee04dbe729391b0b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "9bdd3909b5bc0f6b1d1f4dddce7e68af2ac52400c6233ce135045587d42b82c2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8df8c0325286e1df1d253b8ee04dbe729391b0b"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "9bdd3909b5bc0f6b1d1f4dddce7e68af2ac52400c6233ce135045587d42b82c2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "575c687052dbfbe68465002c3d1328ec92dbb995"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "8cb13f88f817c4b2e6ae175941534a7a15c70226c9187e1165f3a264152699de"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "575c687052dbfbe68465002c3d1328ec92dbb995"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "8cb13f88f817c4b2e6ae175941534a7a15c70226c9187e1165f3a264152699de"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "2093627bb3e3d47d8d21038d7c3ffb3bb1f38666"
os = "windows"

    [[Rclone.download]]
    sha256 = "a9e3867ccdc2f08da0442fb2fddc163ceb50df60ba84d43cdec41a527356af43"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "9e3c675c26738c94ae9645be89b794292c69f93b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f1352fb0f34051512d08922bf6124abd64f9fa90482b70aad4fcf417316fddd1"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "riscv64"
git-tree-sha1 = "17a300390848b01cecffd32b6074eb8c057bdc34"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "03e40b2b060b79b3a398610a660ae26953d5a86f07420601e356bda04c941334"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.riscv64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "3ee8d8ab315e0c66aa8591af6bedf8981426e896"
os = "macos"

    [[Rclone.download]]
    sha256 = "b11fd21eee2533c7188864581ff15ade7d034b35624122f3dbd4eb8df0c0c4ab"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "f063c0be713b23f9154be4eec4c96800387338a2"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "7c506cc0c59256d7dc24e756774ab81de8c2fc5f5d5ed4070a53b2757f80e057"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "23248aac727ba6812186b7242eded3833cb27059"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "29d49ce5c5a720b4cc848a15e2f90edaf0b4616de2f19ae69711c326ad3908e2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "97838e5da6bd58a54c327538bf44259e6f9b4e55"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "aeecc5b1c06c56e17ddbffe6c3751d09714aa3c13e0bdba8474e7fee9007c1ba"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "6c13e3c6aee47ef74fa687b0ca34e91f545a67b4"
os = "windows"

    [[Rclone.download]]
    sha256 = "358399c4ddd672b8a9f627f0cbdfddba1a3ac0466d05d62adcfd89f169043f12"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.70.3+0/Rclone.v1.70.3.x86_64-w64-mingw32.tar.gz"
