[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "d5803ee31329caabb2e69366af57fa6c78739bec"
os = "macos"

    [[Rclone.download]]
    sha256 = "aa4a55903acf9072deb28a5d6b65702e3f8db1a613d297a2246e3fa43ced1f5f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "caeeb5ed7b016e5dc89175392021b56104a60307"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "1d671b8d7bb59873d6f187f6a63eb76b6cf22b22f2c36a687c829cbf35ed3270"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "caeeb5ed7b016e5dc89175392021b56104a60307"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "1d671b8d7bb59873d6f187f6a63eb76b6cf22b22f2c36a687c829cbf35ed3270"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "0e1e6948519a6a756862f40c2e5aef9abcf50570"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "439408470811082e9e33fb95e07657d9ea45444d9bade8a102d25ed7892c3f26"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "904614a6374cfaaaa569c5e246aa36110bd09cb5"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "336d9d075589788ca64ed833ede91119d1ad720b242c6545adc639b7d037d222"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "904614a6374cfaaaa569c5e246aa36110bd09cb5"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "336d9d075589788ca64ed833ede91119d1ad720b242c6545adc639b7d037d222"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2505abf935050bae9578ec0ea4d08a4301bef85"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "3c2cf38bce5eedf4460257d89c46b6000b8c0747eb2bf5c84777577fccb82882"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f2505abf935050bae9578ec0ea4d08a4301bef85"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "3c2cf38bce5eedf4460257d89c46b6000b8c0747eb2bf5c84777577fccb82882"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "6e515c74bce44bdcea4eb27e2b723c5b504cfa8f"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "22914497a8cb0d3a308b7f6a0cbdac1d2d0a2d313d5f2c2ca976d11b9632c194"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "6e515c74bce44bdcea4eb27e2b723c5b504cfa8f"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "22914497a8cb0d3a308b7f6a0cbdac1d2d0a2d313d5f2c2ca976d11b9632c194"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "bb6b8cee475d7cb2fcf2996730eedd9fe4297351"
os = "windows"

    [[Rclone.download]]
    sha256 = "a3285e10f5bca9f42537c771d353e889ff214d140ed2d8a7e6bafc925120b9a2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "b79b94f33d74733967b608b1a5b66a2b7f6f7c2a"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "c85a79816db75f38675c0a3a069b135c0a9a8f58d40f87dfd15e012305208844"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "riscv64"
git-tree-sha1 = "cbfb1e8842ba84cb95e957a82a1e3edba7e9c48c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d28e297c75ee4617778a624973e729a65d2df71daf70fe944ae2e5074d6df60f"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.riscv64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "8d7e8559cd7400bcf4fe782bc6954dee8c465817"
os = "macos"

    [[Rclone.download]]
    sha256 = "43aa4802073ae8cf32292748939d45eb50f5910ee28606a588381371989aa263"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "cfd536316d7c6c8de4f869ef5af7c6fdd92a1f36"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "9088030b81ac42a09f36b6f908cfc7e4678a120ae25e2be1b667ca9de9634b7d"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "79765b098e3a61fa1efd771f9ebfdc7001c44204"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "932542744bde33bd7f9e0d58484a17c0083af171e9fe92ee1c2ed63a3b16ecbf"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "19a51f771aa5612b14fe068494fa41304459cbeb"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "a02af00ace3f163072793c14d7d70ceab259a26e67a0c134eda86987ac1a05cf"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "73ffca4c92eb9cd935ae8ce351783318dc9120af"
os = "windows"

    [[Rclone.download]]
    sha256 = "85874b2a68f67c0719ff618f80422d3e21db0690bda5e2bfe1195fc2090f5a91"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.5+0/Rclone.v1.73.5.x86_64-w64-mingw32.tar.gz"
