[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "38043a506303838d44e1fae2b34e47c3550a2698"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "ddbcc82d93989bc91131c1ab508e7d04d9074f03eef109855140f1b1b26382ba"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "1deb6897ee8cc0fe97b86a2bb7297e395778d833"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "ae85b2ce778ef50922ac58cbc155135eb8b055cb6c154b509f7ab839568d9c30"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a5bf897068def10d1e2b524709233b6ca0cb5ce1"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d559abf92155cd320cc99ee0d9989ef34a4c283c63c1cd892a48129032dc38b4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c4bbf4686f08536f4d2423d22e2c6423be4914b6"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "15146d83472e86928e0acfe24d261d80c6797e657c6c9b80504144ceae331d94"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "c2ac893dc9d457fd7d3badebd41cf24945f3a15b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "f4704e8dd836d295a7970eeed08c747c89c2a84e72f696655af307d0f2ea9d38"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "fc2c7e1ebf6d62d4be7a45d7533baef20a22a55c"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "2b15a4c6767f836bbbe073389d3ca70e053d954880f369db5dd1ac0b0e44ada0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "b322dfa81c024deb122edd7ffe8fc622dbbbb112"
os = "windows"

    [[Rclone.download]]
    sha256 = "feed540a29e8e1edfa4b8e92d05aa873da11629de387b945c2f4e37db95f29ad"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "51ebed1a214b71afd1a23c5ca1581dbd63dbe30b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "43cb15f025c655ef1e6db88dbc802e15ae247d3b7dbbc1ad28ce7cfeb4bee6b7"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "2ab9a5e49abbad76688ac0417feaee4a49aaff78"
os = "macos"

    [[Rclone.download]]
    sha256 = "c85b05490a2e5ca9c228d8d31303cd30225f67c5ed1600165dd202464518d328"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "6b1791a6bd62bec2be7029f9fb52d340559c0360"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "412f8a328410cff808ecafb2031f67b7ac0f4e80ae96db505c81dca6c97739f3"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "cd9522c9ed2dae63bc600db767029be2b42188be"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "01da37b36143c63084bc5b33870b395faab50046cf1be12beb13812f3faf5dbd"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "7259aaf34fc5ca65791443f0dc111c97da0e99d7"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "49dac9e061e9ac632c19d942b8ac914d229a80c953659f559eb728e6f03a0d4d"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "dec7efe75fa0787c6a17669355f4aa6523f156dc"
os = "windows"

    [[Rclone.download]]
    sha256 = "02c289a8297e31e8a0ab932da586f3302a5f4a49b2b13cc04c818839f3c6173b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.53.2+0/Rclone.v1.53.2.x86_64-w64-mingw32.tar.gz"
