[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "6839cdf844f2288fd895e6d6a1c5b1810e510e80"
os = "macos"

    [[Rclone.download]]
    sha256 = "5766fef8f0ad4b5f68d7ed3c83ba7b1ff74147af68523ee387cabec9d623b862"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "853c0b0ead22cda3f818637c0184b9b9ff9e7c54"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "39f2b227d871ecbeee3c6aa60642bb4c3b85ea5d0c60577a3f5761f55ab89d2b"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "3ac6cc4088c9644daab1723d7e54ac13bf23fc37"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "0c1048331e2b8227b27ff9708fe36be775ef11c1c0ba296ff1674457fe3114b0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "236cde88d9753556ba23afe9a337f1e9cb14d63b"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "a70d40f0f471fe5637e23b5cee553792ce931e388b26db964c5a6e9cc5334384"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3889074de9f6773bdfd2187888aa1cdaeb2660d8"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "59cc5d6e903699a588a6e8b95071d966bec0866aa3cf660c1eb95404b397f313"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb49a4920a4d89b5fbe891f2bbe28d61056fdd1a"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "137c1874a5a142bc0d52961fc14be5f2516e2a7c4a701205a3572746e5716d12"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "87f7165164e8f4737db2b69c38af63ad3b829ff6"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "e0bf12fc8554caa1c656a9664944a07d45ded97d17dd97e967cda21ba746e055"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "f63b9f76132652ef17539b2522c39f6986b3a35f"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "c4c8dcfcbaa2670b8cbba7732437d9484a567620e2f26358b22c570621f7a517"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "115afa447d7733085a664bbcfa1702cd02bbd0ed"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "3325ca3fec9bf9266cee3884531dc6b6d0be4bea2ce94241529486537f5d15c4"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "5fa09ea2bf73f0a6bb3de84a7a74500e0e7e9a8c"
os = "windows"

    [[Rclone.download]]
    sha256 = "c5b7daadb3e3a32beee9827ddd54fa2f83d5edca8eb5de122e5bc746eb69a069"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "9b2af51bc6fe4f248701d2327e71508dbf3f2959"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "cd4303b5125b48fac166ae37ec03d169da080398b6e69e816b5d9257bc7d71e0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "ab76111b18d0fbf3931d683ac28123de8150d389"
os = "macos"

    [[Rclone.download]]
    sha256 = "dd50f27c1b07074eb0820affe7d20f246d3b055d2966b32a8a4bcb77ad886587"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "f89f2b92295c2b22b2af45265b4bf8dd221234a4"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "8aed62ef4d38611b82ce521a39ec844124d496e06edfce374f91760e88d4f3a8"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "740b919edfc592cd5b783935675461c554f310ef"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "8b5ccbc4ad125042a26894b4c11077a2fb873d809c00b5ce7eae6910b0bf50a9"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "c57548e36ba64aab7e16ed1afda63b6d63253f4d"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "9b6b1a0fe148b531f9c45fca84505a05c7aa39f611aae2051a00337a8e72d7fd"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "38997c7ae3b94ad47f9c9d70a15ad9ebeb9266a2"
os = "windows"

    [[Rclone.download]]
    sha256 = "d53e2e38abfc623080e21f3fd5f1259bcc7a6d27e13abc7436b3ab8792b883f2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.55.1+0/Rclone.v1.55.1.x86_64-w64-mingw32.tar.gz"
