[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "86bdfcffadaa94bce137587f3a9787ee82626e1b"
os = "macos"

    [[Rclone.download]]
    sha256 = "ed6d420d79cafcbd994e6d15df758f9162a9ad496746fbbc85ec8e358240b6fe"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.aarch64-apple-darwin.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "62e624b842fdee89fe8976e64d9cc5444b09525c"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "a02a6d4f59b2d4b401eafc455b207940c2aec7f8a88b6ae50ef9503f84574616"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.aarch64-linux-gnu.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "62e624b842fdee89fe8976e64d9cc5444b09525c"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "a02a6d4f59b2d4b401eafc455b207940c2aec7f8a88b6ae50ef9503f84574616"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.aarch64-linux-musl.tar.gz"
[[Rclone]]
arch = "aarch64"
git-tree-sha1 = "42aa01e0ec4c4ab583f1b7985ae6bcb2a79a5ac1"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "5e0a877f373c1a4902183d94a48bf0a80c39fd92079fb2c12ec9e3f6ca1b63ed"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.aarch64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3d23869afcad80423ab82a9be4494a5578acef6"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "8d7ab4b56d9682d9ba10317c6a3ee0eab58beec882a83ed641552ec2df0680ff"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.armv6l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3d23869afcad80423ab82a9be4494a5578acef6"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "8d7ab4b56d9682d9ba10317c6a3ee0eab58beec882a83ed641552ec2df0680ff"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.armv6l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "278be2f2dedd7ded048b50e9b0e3746cbe72d5ed"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "a83d95b67806e1c958e34ffc0f81cafc9f9429aefb8637807d6535f14dcfe857"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.armv7l-linux-gnueabihf.tar.gz"
[[Rclone]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "278be2f2dedd7ded048b50e9b0e3746cbe72d5ed"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "a83d95b67806e1c958e34ffc0f81cafc9f9429aefb8637807d6535f14dcfe857"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.armv7l-linux-musleabihf.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "1489f76ed123425f3986842d96c9cd67e6422e06"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "84f3be68efb6bff4a15b031836bc3fb002fee26b195fdd4d9f71dc04c12876d0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.i686-linux-gnu.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "1489f76ed123425f3986842d96c9cd67e6422e06"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "84f3be68efb6bff4a15b031836bc3fb002fee26b195fdd4d9f71dc04c12876d0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.i686-linux-musl.tar.gz"
[[Rclone]]
arch = "i686"
git-tree-sha1 = "11cc8af6629266253554eeafc4af44c8dee7842b"
os = "windows"

    [[Rclone.download]]
    sha256 = "8ec25fc53c5050a21017326e4de942c0d380f49e35c22006e5e09ccc0558eef2"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.i686-w64-mingw32.tar.gz"
[[Rclone]]
arch = "powerpc64le"
git-tree-sha1 = "4b1e6b98d936b029333d70724215319ea6698675"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "d5e6599c8122f0eff6ce8183920cb2380023d245441c68ff8a9708fef5d97625"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.powerpc64le-linux-gnu.tar.gz"
[[Rclone]]
arch = "riscv64"
git-tree-sha1 = "cea45f347f9dd5123eff35f11951005750fca459"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "9388fcd2b231ff9c5f5e7e6f68821ebda02a38ecb096f66419d99551d864fc09"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.riscv64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "361c478a7b06e672f23de8410c30aa6e861294ed"
os = "macos"

    [[Rclone.download]]
    sha256 = "de47a66ce8b4f880e3314ad4c29e02d4b2bd5d468db4a650d7cd7588756c26b6"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.x86_64-apple-darwin.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "f76bbe1dcb9d18b0adc7c539da81e3f7a781f286"
libc = "glibc"
os = "linux"

    [[Rclone.download]]
    sha256 = "e0bad1209273bbcba1998a09e710c8181d49c2561d949385ff74a9e61464c001"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.x86_64-linux-gnu.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "59d8c58dd18845fb446136b8958122d3eca78d4d"
libc = "musl"
os = "linux"

    [[Rclone.download]]
    sha256 = "e267ce853e8acf53e13714a577b3e5819fc8c27dfc83e20130d862bd1718b379"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.x86_64-linux-musl.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "05dd8081186895f0ddf9ce88104a7a07115c9012"
os = "freebsd"

    [[Rclone.download]]
    sha256 = "00495f0466a41e30057008c596f7135817c83fdf662c5fd99f4ac446109a6588"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.x86_64-unknown-freebsd.tar.gz"
[[Rclone]]
arch = "x86_64"
git-tree-sha1 = "a55a4125f81f98905ca6274e09cc26fdceb38f81"
os = "windows"

    [[Rclone.download]]
    sha256 = "79e701c9c40f658d0c38835feefe5c83134502db1c26870a390124f957cb0fb0"
    url = "https://github.com/JuliaBinaryWrappers/Rclone_jll.jl/releases/download/Rclone-v1.73.3+0/Rclone.v1.73.3.x86_64-w64-mingw32.tar.gz"
